### ISSUE TITLE
Groomsmen Night Out

### ISSUE THREAD

**Issue by shayanik** [shayanik/Shayannon-Wedding#2]
Need to accomplish the following:
- Choose a date
- Choose a restaurant
- Make reservations
- Decide on any other activities

**Comment by shayanik** [comment]
http://www.foodwineandco.com/

**Comment by shayanik** [comment]
The plan is:
- Meet at Shayan's and collectively have a glass of Hibiki
- Head to restaurant for dinner
- Drinks somewhere

**Comment by shayanik** [comment]
Transportation: 2 Uber blacks is the idea for now

**Comment by shayanik** [comment]
Mike, we should probably get everyone to pay for their portion soon. You have Venmo, right?  I can send out an email to everyone and ask who else does? If not that, maybe paypal? All you need is the email registered to their account I think. I can tackle this for you, I just need to know what you prefer to do.

**Comment by mihorhino** [comment]
Yeah, I'll give people a couple options for repayment. I'll handle this.

On Tue, Mar 22, 2016 at 12:52 PM, Shayan Kheradmand <
notifications@github.com> wrote:

> Mike, we should probably get everyone to pay for their portion soon. You
> have Venmo, right? I can send out an email to everyone and ask who else
> does? If not that, maybe paypal? All you need is the email registered to
> their account I think. I can tackle this for you, I just need to know what
> you prefer to do.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/shayanik/Shayannon-Wedding/issues/2#issuecomment-199902515>
>



-- 
Michael H. Chen
(c): 301.704.9248
(e): michael.h.chen@gmail.com
